# -*- coding: utf-8 -*-
"""TextSummarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JSIj0BY3da16WlZdKEbPoLkTTJYP_Dk
"""

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer

text = """
Artificial intelligence is transforming many industries.
It enables machines to learn from data and make decisions.
AI is widely used in healthcare, finance, and education.
However, ethical concerns such as bias and privacy remain.
"""

parser = PlaintextParser.from_string(text, Tokenizer("english"))
summarizer = TextRankSummarizer()

summary = summarizer(parser.document, 2)

print("Extractive Summary:")
for sentence in summary:
    print(sentence)

!pip install sumy nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

